# syntax = docker/dockerfile:1.0-experimental
ARG TAG=latest
FROM hysds/verdi:${TAG}

MAINTAINER Gerald Manipon (pymonger) "pymonger@gmail.com"
LABEL description="HySDS base PGE (product generation executor) image"

# set entrypoint
COPY docker/entrypoint* /
ENTRYPOINT ["/entrypoint-pge.sh"]
CMD ["/bin/bash", "--login"]
