# .bash_profile

# Get the aliases and functions
if [ -f ~/.bashrc ]; then
    . ~/.bashrc
fi

# misc
umask 0022
export GIT_SSL_NO_VERIFY=true

# source verdi virtualenv if exists
export VERDI_DIR=$HOME/verdi
if [ -e "$VERDI_DIR/bin/activate" ]; then
  source $VERDI_DIR/bin/activate
fi
