# .bash_profile

# Get the aliases and functions
if [ -f ~/.bashrc ]; then
    . ~/.bashrc
fi

# misc
umask 0022
export LD_LIBRARY_PATH=/opt/conda/lib:/usr/lib:/usr/lib64:/usr/local/lib:$LD_LIBRARY_PATH
export GIT_SSL_NO_VERIFY=true
export PATH=${conda_path}/bin:$PATH

# source verdi virtualenv
export VERDI_DIR=$HOME/verdi
source $VERDI_DIR/bin/activate
